import { Card, LegalSection, PageLayout } from "@/components";
import { Text, View } from "react-native";

const personalInfo = [
  "Email address",
  "Name (if provided via Google authentication)",
  "Profile information from your Google account",
];

const resumeData = [
  "Resume content you upload",
  "Job posting links you submit",
  "Analysis results and feedback generated by our AI",
];

const usageInfo = [
  "Device information (type, operating system)",
  "Usage data (features accessed, time spent)",
  "Error logs and diagnostic information",
];

const howWeUseData = [
  "Provide, maintain, and improve our services",
  "Analyze your resume against job postings",
  "Generate personalized feedback and recommendations",
  "Send you technical notices and support messages",
  "Respond to your comments and questions",
  "Protect against fraudulent or illegal activity",
];

const securityMeasures = [
  "End-to-end encryption for data transmission",
  "Secure cloud storage with encryption at rest",
  "Regular security audits and updates",
  "Limited access to personal data by authorized personnel only",
];

const sharingCircumstances = [
  "With service providers who help us operate our platform (e.g., cloud hosting, AI services)",
  "When required by law or to protect our rights",
  "With your explicit consent",
];

const privacyRights = [
  "Access your personal data",
  "Correct inaccurate or incomplete data",
  "Request deletion of your data",
  "Object to or restrict processing of your data",
  "Export your data in a portable format",
];

export default function PrivacyPolicyPage() {
  return (
    <PageLayout>
      <Text className="text-white text-4xl font-bold mb-4">
        Privacy Policy
      </Text>
      <Text className="text-zinc-500 text-sm mb-12">
        Last updated: January 2025
      </Text>
      <View className="mb-10">
        <Text className="text-zinc-400 text-base leading-relaxed mb-4">
          At Resume Pivot, we take your privacy seriously. This Privacy Policy
          explains how we collect, use, disclose, and safeguard your information
          when you use our mobile application and services.
        </Text>
        <Text className="text-zinc-400 text-base leading-relaxed">
          Please read this privacy policy carefully. If you do not agree with
          the terms of this privacy policy, please do not access the
          application.
        </Text>
      </View>
      <LegalSection title="Information We Collect">
        <LegalSection subtitle="Personal Information">
          <Text className="text-zinc-400 text-base leading-relaxed mb-4">
            When you register for an account, we may collect:
          </Text>
          <Card>
            {personalInfo.map((item, index) => (
              <Text
                key={index}
                className={`text-zinc-300 text-sm ${index < personalInfo.length - 1 ? "mb-2" : ""}`}
              >
                • {item}
              </Text>
            ))}
          </Card>
        </LegalSection>
        <LegalSection subtitle="Resume Data">
          <Text className="text-zinc-400 text-base leading-relaxed mb-4">
            To provide our services, we collect and process:
          </Text>
          <Card>
            {resumeData.map((item, index) => (
              <Text
                key={index}
                className={`text-zinc-300 text-sm ${index < resumeData.length - 1 ? "mb-2" : ""}`}
              >
                • {item}
              </Text>
            ))}
          </Card>
        </LegalSection>
        <LegalSection subtitle="Usage Information">
          <Text className="text-zinc-400 text-base leading-relaxed mb-4">
            We automatically collect certain information when you use ResumeShift:
          </Text>
          <Card>
            {usageInfo.map((item, index) => (
              <Text
                key={index}
                className={`text-zinc-300 text-sm ${index < usageInfo.length - 1 ? "mb-2" : ""}`}
              >
                • {item}
              </Text>
            ))}
          </Card>
        </LegalSection>
      </LegalSection>
      <LegalSection title="How We Use Your Information">
        <Text className="text-zinc-400 text-base leading-relaxed mb-4">
          We use the information we collect to:
        </Text>
        <Card>
          {howWeUseData.map((item, index) => (
            <Text
              key={index}
              className={`text-zinc-300 text-sm ${index < howWeUseData.length - 1 ? "mb-2" : ""}`}
            >
              • {item}
            </Text>
          ))}
        </Card>
      </LegalSection>
      <LegalSection title="Data Security">
        <Text className="text-zinc-400 text-base leading-relaxed mb-4">
          We implement appropriate technical and organizational security measures
          to protect your personal information:
        </Text>
        <Card>
          {securityMeasures.map((item, index) => (
            <Text
              key={index}
              className={`text-zinc-300 text-sm ${index < securityMeasures.length - 1 ? "mb-2" : ""}`}
            >
              • {item}
            </Text>
          ))}
        </Card>
      </LegalSection>
      <LegalSection title="Data Sharing and Disclosure">
        <Text className="text-zinc-400 text-base leading-relaxed mb-4">
          We do not sell, rent, or trade your personal information to third
          parties. We may share your information only in the following
          circumstances:
        </Text>
        <Card>
          {sharingCircumstances.map((item, index) => (
            <Text
              key={index}
              className={`text-zinc-300 text-sm ${index < sharingCircumstances.length - 1 ? "mb-2" : ""}`}
            >
              • {item}
            </Text>
          ))}
        </Card>
      </LegalSection>
      <LegalSection title="Data Retention">
        <Text className="text-zinc-400 text-base leading-relaxed">
          We retain your personal information for as long as necessary to provide
          our services and fulfill the purposes outlined in this privacy policy.
          You may request deletion of your account and associated data at any
          time by contacting us.
        </Text>
      </LegalSection>
      <LegalSection title="Your Privacy Rights">
        <Text className="text-zinc-400 text-base leading-relaxed mb-4">
          Depending on your location, you may have the following rights:
        </Text>
        <Card>
          {privacyRights.map((item, index) => (
            <Text
              key={index}
              className={`text-zinc-300 text-sm ${index < privacyRights.length - 1 ? "mb-2" : ""}`}
            >
              • {item}
            </Text>
          ))}
        </Card>
      </LegalSection>
      <LegalSection title="Contact Us">
        <Text className="text-zinc-400 text-base leading-relaxed mb-4">
          If you have questions or concerns about this Privacy Policy, please
          contact us at:
        </Text>
        <Card>
          <Text className="text-zinc-300 text-sm">privacy@resumeshift.com</Text>
        </Card>
      </LegalSection>
      <LegalSection title="Changes to This Privacy Policy">
        <Text className="text-zinc-400 text-base leading-relaxed">
          We may update this Privacy Policy from time to time. We will notify
          you of any changes by posting the new Privacy Policy on this page and
          updating the "Last updated" date.
        </Text>
      </LegalSection>
    </PageLayout>
  );
}
